### ISSUE TITLE
Page for reviewing collected data

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/log-detective-website#4]
I imagine it to look exactly the same as the contribute page.

- 3 columns (instructions, logs, comments)
- ~Everything read-only~
- ~Every comment in the right column would have a separate +1, -1 buttons~
- Allow reviewers to edit the values, keep history, add reviewer to reviewers

We need:
 * [ ] frontend part of review collected data (the page itself)
 * [ ] backend part of review collected data
 * [ ] alter frontpage to give option to review data

**Comment by xsuchy** [comment]
Removing release-blocker. We can do this after release in next phase.

**Comment by xsuchy** [comment]
I would like to get an inspiration from https://commonvoice.mozilla.org/cs (listen part)

**Comment by FrostyX** [comment]
> Every comment in the right column would have a separate +1, -1 buttons

We decided on meeting that we want users to allow editing the fields instead of +1 and -1 and ideally keep a history of the changes.

**Comment by FrostyX** [comment]
We agreed that I will be working on the frontend code and David will review it. @nikromen are you interested in doing the backend part? Like we did previously.

**Comment by FrostyX** [comment]
For the record, it is being developed in https://github.com/fedora-copr/log-detective-website/commits/review/
